# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_time', models.DateTimeField(auto_now=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('Vrms', models.DecimalField(decimal_places=3, max_digits=8)),
                ('Irms', models.DecimalField(decimal_places=3, max_digits=8)),
                ('Irms2', models.DecimalField(decimal_places=3, max_digits=8)),
                ('Pa', models.DecimalField(decimal_places=3, max_digits=8)),
                ('Preact', models.DecimalField(decimal_places=3, max_digits=8)),
                ('Preal', models.DecimalField(decimal_places=3, max_digits=8)),
                ('site', models.TextField()),
            ],
        ),
    ]
